### ISSUE TITLE
out of sync with cjdelisle/cjdns

### ISSUE THREAD

**Issue by ansuz** [hyperboria/docs#52]

**Comment by kpcyrd** [comment]
Following the destiny of hyperboria/cjdns, we should either:
- deprecate this repo
- remove docs/ from cjdelisle/cjdns and declare this repo the official documentation

It's probably wise to have a (clearly) official github org that keeps track of meta repos, like `bugs`, `docs` and similar. The hyperboria org currently sort-of does that, but the name is suboptimal since you need to know a lot about the project to know that it's official-ish. Does anybody know who owns the cjdns org?

**Comment by ansuz** [comment]
omg there's a cjdns org now too?

**Comment by ansuz** [comment]
D:

**Comment by ansuz** [comment]
name squatters probably.

**Comment by ansuz** [comment]
I like the idea of people having the documentation available as a default once they've installed cjdns, but in practice it makes it really difficult to maintain this because people keep PRing the other repo, and merges suck.

At this point this is a big steaming mess and it takes a lot of git-fu to be able to figure it out.
